// flow-typed signature: a67e157226affde66cb320d59ac203c8
// flow-typed version: <<STUB>>/react-html-document_v^3.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-document'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html-document' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html-document/dist/client' {
  declare module.exports: any;
}

declare module 'react-html-document/dist/constants' {
  declare module.exports: any;
}

declare module 'react-html-document/dist/HTMLDocument' {
  declare module.exports: any;
}

declare module 'react-html-document/dist/index' {
  declare module.exports: any;
}

declare module 'react-html-document/dist/readFile' {
  declare module.exports: any;
}

declare module 'react-html-document/example-usage-server' {
  declare module.exports: any;
}

declare module 'react-html-document/src/client' {
  declare module.exports: any;
}

declare module 'react-html-document/src/constants' {
  declare module.exports: any;
}

declare module 'react-html-document/src/HTMLDocument' {
  declare module.exports: any;
}

declare module 'react-html-document/src/index' {
  declare module.exports: any;
}

declare module 'react-html-document/src/readFile' {
  declare module.exports: any;
}

declare module 'react-html-document/test/client.spec' {
  declare module.exports: any;
}

declare module 'react-html-document/test/HTMLDocument.spec' {
  declare module.exports: any;
}

declare module 'react-html-document/test/readFile.spec' {
  declare module.exports: any;
}

declare module 'react-html-document/test/test-script' {
  declare module.exports: any;
}

declare module 'react-html-document/test/TestApp' {
  declare module.exports: any;
}

declare module 'react-html-document/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html-document/dist/client.js' {
  declare module.exports: $Exports<'react-html-document/dist/client'>;
}
declare module 'react-html-document/dist/constants.js' {
  declare module.exports: $Exports<'react-html-document/dist/constants'>;
}
declare module 'react-html-document/dist/HTMLDocument.js' {
  declare module.exports: $Exports<'react-html-document/dist/HTMLDocument'>;
}
declare module 'react-html-document/dist/index.js' {
  declare module.exports: $Exports<'react-html-document/dist/index'>;
}
declare module 'react-html-document/dist/readFile.js' {
  declare module.exports: $Exports<'react-html-document/dist/readFile'>;
}
declare module 'react-html-document/example-usage-server.js' {
  declare module.exports: $Exports<'react-html-document/example-usage-server'>;
}
declare module 'react-html-document/src/client.js' {
  declare module.exports: $Exports<'react-html-document/src/client'>;
}
declare module 'react-html-document/src/constants.js' {
  declare module.exports: $Exports<'react-html-document/src/constants'>;
}
declare module 'react-html-document/src/HTMLDocument.jsx' {
  declare module.exports: $Exports<'react-html-document/src/HTMLDocument'>;
}
declare module 'react-html-document/src/index.js' {
  declare module.exports: $Exports<'react-html-document/src/index'>;
}
declare module 'react-html-document/src/readFile.js' {
  declare module.exports: $Exports<'react-html-document/src/readFile'>;
}
declare module 'react-html-document/test/client.spec.js' {
  declare module.exports: $Exports<'react-html-document/test/client.spec'>;
}
declare module 'react-html-document/test/HTMLDocument.spec.js' {
  declare module.exports: $Exports<'react-html-document/test/HTMLDocument.spec'>;
}
declare module 'react-html-document/test/readFile.spec.js' {
  declare module.exports: $Exports<'react-html-document/test/readFile.spec'>;
}
declare module 'react-html-document/test/test-script.js' {
  declare module.exports: $Exports<'react-html-document/test/test-script'>;
}
declare module 'react-html-document/test/TestApp.jsx' {
  declare module.exports: $Exports<'react-html-document/test/TestApp'>;
}
declare module 'react-html-document/test/utils.js' {
  declare module.exports: $Exports<'react-html-document/test/utils'>;
}
