// flow-typed signature: 65352212d15d44db934e08eb01616bc7
// flow-typed version: <<STUB>>/react-burger-menu_v^1.10.8/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-burger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-burger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-burger-menu/dist/react-burger-menu' {
  declare module.exports: any;
}

declare module 'react-burger-menu/dist/react-burger-menu.min' {
  declare module.exports: any;
}

declare module 'react-burger-menu/example/src/example' {
  declare module.exports: any;
}

declare module 'react-burger-menu/gulpfile' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/baseStyles' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/BurgerIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/BurgerMenu' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/CrossIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menuFactory' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/bubble' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/elastic' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/fallDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/push' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/pushRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/scaleDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/scaleRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/slide' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/stack' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/snapsvgImporter' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/baseStyles' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/BurgerIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/BurgerMenu' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/CrossIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menuFactory' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/bubble' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/elastic' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/fallDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/push' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/pushRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/scaleDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/scaleRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/slide' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/menus/stack' {
  declare module.exports: any;
}

declare module 'react-burger-menu/src/snapsvgImporter' {
  declare module.exports: any;
}

declare module 'react-burger-menu/tasks/release' {
  declare module.exports: any;
}

declare module 'react-burger-menu/tasks/test' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/baseStyles.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/bubble.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/BurgerIcon.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/CrossIcon.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/elastic.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/fallDown.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/menuFactory.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/push.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/pushRotate.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/scaleDown.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/scaleRotate.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/slide.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/stack.spec' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/utils/createShallowComponent' {
  declare module.exports: any;
}

declare module 'react-burger-menu/test/utils/dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-burger-menu/dist/react-burger-menu.js' {
  declare module.exports: $Exports<'react-burger-menu/dist/react-burger-menu'>;
}
declare module 'react-burger-menu/dist/react-burger-menu.min.js' {
  declare module.exports: $Exports<'react-burger-menu/dist/react-burger-menu.min'>;
}
declare module 'react-burger-menu/example/src/example.js' {
  declare module.exports: $Exports<'react-burger-menu/example/src/example'>;
}
declare module 'react-burger-menu/gulpfile.js' {
  declare module.exports: $Exports<'react-burger-menu/gulpfile'>;
}
declare module 'react-burger-menu/lib/baseStyles.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/baseStyles'>;
}
declare module 'react-burger-menu/lib/BurgerIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/BurgerIcon'>;
}
declare module 'react-burger-menu/lib/BurgerMenu.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/BurgerMenu'>;
}
declare module 'react-burger-menu/lib/CrossIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/CrossIcon'>;
}
declare module 'react-burger-menu/lib/menuFactory.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menuFactory'>;
}
declare module 'react-burger-menu/lib/menus/bubble.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/bubble'>;
}
declare module 'react-burger-menu/lib/menus/elastic.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/elastic'>;
}
declare module 'react-burger-menu/lib/menus/fallDown.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/fallDown'>;
}
declare module 'react-burger-menu/lib/menus/push.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/push'>;
}
declare module 'react-burger-menu/lib/menus/pushRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/pushRotate'>;
}
declare module 'react-burger-menu/lib/menus/scaleDown.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/scaleDown'>;
}
declare module 'react-burger-menu/lib/menus/scaleRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/scaleRotate'>;
}
declare module 'react-burger-menu/lib/menus/slide.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/slide'>;
}
declare module 'react-burger-menu/lib/menus/stack.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/stack'>;
}
declare module 'react-burger-menu/lib/snapsvgImporter.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/snapsvgImporter'>;
}
declare module 'react-burger-menu/src/baseStyles.js' {
  declare module.exports: $Exports<'react-burger-menu/src/baseStyles'>;
}
declare module 'react-burger-menu/src/BurgerIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/src/BurgerIcon'>;
}
declare module 'react-burger-menu/src/BurgerMenu.js' {
  declare module.exports: $Exports<'react-burger-menu/src/BurgerMenu'>;
}
declare module 'react-burger-menu/src/CrossIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/src/CrossIcon'>;
}
declare module 'react-burger-menu/src/menuFactory.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menuFactory'>;
}
declare module 'react-burger-menu/src/menus/bubble.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/bubble'>;
}
declare module 'react-burger-menu/src/menus/elastic.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/elastic'>;
}
declare module 'react-burger-menu/src/menus/fallDown.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/fallDown'>;
}
declare module 'react-burger-menu/src/menus/push.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/push'>;
}
declare module 'react-burger-menu/src/menus/pushRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/pushRotate'>;
}
declare module 'react-burger-menu/src/menus/scaleDown.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/scaleDown'>;
}
declare module 'react-burger-menu/src/menus/scaleRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/scaleRotate'>;
}
declare module 'react-burger-menu/src/menus/slide.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/slide'>;
}
declare module 'react-burger-menu/src/menus/stack.js' {
  declare module.exports: $Exports<'react-burger-menu/src/menus/stack'>;
}
declare module 'react-burger-menu/src/snapsvgImporter.js' {
  declare module.exports: $Exports<'react-burger-menu/src/snapsvgImporter'>;
}
declare module 'react-burger-menu/tasks/release.js' {
  declare module.exports: $Exports<'react-burger-menu/tasks/release'>;
}
declare module 'react-burger-menu/tasks/test.js' {
  declare module.exports: $Exports<'react-burger-menu/tasks/test'>;
}
declare module 'react-burger-menu/test/baseStyles.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/baseStyles.spec'>;
}
declare module 'react-burger-menu/test/bubble.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/bubble.spec'>;
}
declare module 'react-burger-menu/test/BurgerIcon.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/BurgerIcon.spec'>;
}
declare module 'react-burger-menu/test/CrossIcon.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/CrossIcon.spec'>;
}
declare module 'react-burger-menu/test/elastic.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/elastic.spec'>;
}
declare module 'react-burger-menu/test/fallDown.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/fallDown.spec'>;
}
declare module 'react-burger-menu/test/menuFactory.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/menuFactory.spec'>;
}
declare module 'react-burger-menu/test/push.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/push.spec'>;
}
declare module 'react-burger-menu/test/pushRotate.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/pushRotate.spec'>;
}
declare module 'react-burger-menu/test/scaleDown.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/scaleDown.spec'>;
}
declare module 'react-burger-menu/test/scaleRotate.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/scaleRotate.spec'>;
}
declare module 'react-burger-menu/test/slide.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/slide.spec'>;
}
declare module 'react-burger-menu/test/stack.spec.js' {
  declare module.exports: $Exports<'react-burger-menu/test/stack.spec'>;
}
declare module 'react-burger-menu/test/utils/createShallowComponent.js' {
  declare module.exports: $Exports<'react-burger-menu/test/utils/createShallowComponent'>;
}
declare module 'react-burger-menu/test/utils/dom.js' {
  declare module.exports: $Exports<'react-burger-menu/test/utils/dom'>;
}
