// flow-typed signature: bad17b91cdbed315a84d6f442bd4d81b
// flow-typed version: <<STUB>>/react-fa_v^4.1.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fa/example/assets/bundle' {
  declare module.exports: any;
}

declare module 'react-fa/example/index' {
  declare module.exports: any;
}

declare module 'react-fa/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-fa/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-fa/lib/IconStack' {
  declare module.exports: any;
}

declare module 'react-fa/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fa/example/assets/bundle.js' {
  declare module.exports: $Exports<'react-fa/example/assets/bundle'>;
}
declare module 'react-fa/example/index.js' {
  declare module.exports: $Exports<'react-fa/example/index'>;
}
declare module 'react-fa/example/webpack.config.js' {
  declare module.exports: $Exports<'react-fa/example/webpack.config'>;
}
declare module 'react-fa/lib/Icon.js' {
  declare module.exports: $Exports<'react-fa/lib/Icon'>;
}
declare module 'react-fa/lib/IconStack.js' {
  declare module.exports: $Exports<'react-fa/lib/IconStack'>;
}
declare module 'react-fa/lib/index.js' {
  declare module.exports: $Exports<'react-fa/lib/index'>;
}
