// flow-typed signature: 1f64aca52e4fd1a3b55c426220bd0885
// flow-typed version: <<STUB>>/react-imgix_v^5.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-imgix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-imgix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-imgix/lib/index' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/support' {
  declare module.exports: any;
}

declare module 'react-imgix/src/index' {
  declare module.exports: any;
}

declare module 'react-imgix/src/index.test' {
  declare module.exports: any;
}

declare module 'react-imgix/src/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-imgix/lib/index.js' {
  declare module.exports: $Exports<'react-imgix/lib/index'>;
}
declare module 'react-imgix/lib/index.test.js' {
  declare module.exports: $Exports<'react-imgix/lib/index.test'>;
}
declare module 'react-imgix/lib/support.js' {
  declare module.exports: $Exports<'react-imgix/lib/support'>;
}
declare module 'react-imgix/src/index.js' {
  declare module.exports: $Exports<'react-imgix/src/index'>;
}
declare module 'react-imgix/src/index.test.js' {
  declare module.exports: $Exports<'react-imgix/src/index.test'>;
}
declare module 'react-imgix/src/support.js' {
  declare module.exports: $Exports<'react-imgix/src/support'>;
}
