// flow-typed signature: ee55fba03695dab4b76247cce92832b9
// flow-typed version: <<STUB>>/redial_v^0.5.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redial'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redial' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redial/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redial/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redial/lib/index' {
  declare module.exports: any;
}

declare module 'redial/lib/propName' {
  declare module.exports: any;
}

declare module 'redial/lib/provideHooks' {
  declare module.exports: any;
}

declare module 'redial/lib/trigger' {
  declare module.exports: any;
}

declare module 'redial/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redial/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redial/coverage/lcov-report/prettify'>;
}
declare module 'redial/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redial/coverage/lcov-report/sorter'>;
}
declare module 'redial/lib/index.js' {
  declare module.exports: $Exports<'redial/lib/index'>;
}
declare module 'redial/lib/propName.js' {
  declare module.exports: $Exports<'redial/lib/propName'>;
}
declare module 'redial/lib/provideHooks.js' {
  declare module.exports: $Exports<'redial/lib/provideHooks'>;
}
declare module 'redial/lib/trigger.js' {
  declare module.exports: $Exports<'redial/lib/trigger'>;
}
declare module 'redial/test/index.js' {
  declare module.exports: $Exports<'redial/test/index'>;
}
