// flow-typed signature: 389971657a07a73a99dc4f542130033b
// flow-typed version: <<STUB>>/webpack-assets-manifest_v^0.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-assets-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-assets-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-assets-manifest/src/CompilationAsset' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/src/WebpackAssetsManifest' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/CompilationAsset-test' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/fixtures/client' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/fixtures/configs' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/fixtures/hello' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/fixtures/makeCompiler' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/fixtures/server' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/test/WebpackAssetsManifest-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-assets-manifest/src/CompilationAsset.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/src/CompilationAsset'>;
}
declare module 'webpack-assets-manifest/src/WebpackAssetsManifest.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/src/WebpackAssetsManifest'>;
}
declare module 'webpack-assets-manifest/test/CompilationAsset-test.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/CompilationAsset-test'>;
}
declare module 'webpack-assets-manifest/test/fixtures/client.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/fixtures/client'>;
}
declare module 'webpack-assets-manifest/test/fixtures/configs.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/fixtures/configs'>;
}
declare module 'webpack-assets-manifest/test/fixtures/hello.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/fixtures/hello'>;
}
declare module 'webpack-assets-manifest/test/fixtures/makeCompiler.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/fixtures/makeCompiler'>;
}
declare module 'webpack-assets-manifest/test/fixtures/server.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/fixtures/server'>;
}
declare module 'webpack-assets-manifest/test/WebpackAssetsManifest-test.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/test/WebpackAssetsManifest-test'>;
}
