import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

import "normalize.css";
import "./layout.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Main from "@/components/Main";

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fi">
      <body>
        <Header />

        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
