// flow-typed signature: cdcc3a5ba0344dce9f3ac89736f4c1b6
// flow-typed version: <<STUB>>/@dr-kobros/html-document-webpack-plugin_v^0.4.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dr-kobros/html-document-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@dr-kobros/html-document-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dr-kobros/html-document-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dr-kobros/html-document-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'@dr-kobros/html-document-webpack-plugin/lib/index'>;
}
